import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { buildHeroine,animateHeroine,setExpression } from './view/heroine.js';
import { buildCat,animateCat } from './view/cat.js';
const canvas=document.querySelector('#gallery');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new THREE.Scene();scene.background=new THREE.Color('#e9ede3');
scene.add(new THREE.HemisphereLight(0xfff5e5,0x7e9a78,2));
const sun=new THREE.DirectionalLight(0xffe5cf,3);sun.position.set(-3,5,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-3;sun.shadow.camera.right=3;sun.shadow.camera.top=3;sun.shadow.camera.bottom=-3;sun.shadow.bias=-.00015;scene.add(sun);
const rim=new THREE.DirectionalLight(0xd5eaff,1.5);rim.position.set(3,3,-3);scene.add(rim);
const floor=new THREE.Mesh(new THREE.CircleGeometry(3,96),new THREE.MeshStandardMaterial({color:0xf5ead7,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const platform=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.1,.085,72),new THREE.MeshStandardMaterial({color:0xf9f0de,roughness:.8}));platform.position.y=-.048;platform.receiveShadow=true;scene.add(platform);
const girl=buildHeroine();girl.position.x=-.30;scene.add(girl);
const cat=buildCat();cat.position.set(.43,.02,.18);cat.rotation.y=-.18;cat.scale.setScalar(1.30);scene.add(cat);
const camera=new THREE.PerspectiveCamera(36,1,.01,50);camera.position.set(1.9,1.65,4.1);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,.86,0);controls.enableDamping=true;controls.minDistance=1.4;controls.maxDistance=6;controls.maxPolarAngle=Math.PI/2-.02;
let pose='idle';document.querySelectorAll('[data-pose]').forEach(button=>button.addEventListener('click',()=>{pose=button.dataset.pose;document.querySelectorAll('[data-pose]').forEach(b=>b.classList.toggle('active',b===button));}));
document.querySelector('#spin').addEventListener('click',e=>{controls.autoRotate=!controls.autoRotate;e.target.classList.toggle('active',controls.autoRotate);});
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
const clock=new THREE.Clock();function frame(){const t=clock.getElapsedTime();animateHeroine(girl,pose==='worried'?'idle':pose,t);setExpression(girl,pose==='worried');animateCat(cat,pose==='work'||pose==='worried'||pose==='shoo'?'reach':pose==='walk'?'walk':'sit',t,pose==='walk'?1:0);controls.update();renderer.render(scene,camera);requestAnimationFrame(frame);}frame();
